config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  resources :operations, except: :index
  get '/income/(:year)/(:month)',
      to: 'operations#index',
      as: :incomes,
      type: 'income'
  get '/outgo/(:year)/(:month)',
      to: 'operations#index',
      as: :outgos,
      type: 'outgo'

  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show', as: :profile
  resource :user, only: :update
  resources :invites, only: %i(create destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
  validates :amount, :year, :month, presence: true
  belongs_to :user
end

app/models/categories/income.rb
class Categories::Income < Category
  has_many :operations,
           class_name: 'Operations::Income',
           through: :operation_categories
end

app/models/categories/outgo.rb
class Categories::Outgo < Category
  has_many :operations,
           class_name: 'Operations::Outgo',
           through: :operation_categories
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 50 }
  validates :title, uniqueness: { scope: [:user_id, :type] }
  has_many :operation_categories, dependent: :destroy
  belongs_to :user

  delegate :family, to: :user
end

app/models/family.rb
class Family < ApplicationRecord
  # TODO: need to validate while user is creating
  MAX_USERS_COUNT = 3
  FREE_MONTH_OPERATIONS_LIMIT = 50
  has_many :users
  has_many :categories, through: :users
  has_many :operations, through: :users
  has_many :invites, through: :users

  def full?
    (users.count + invites.waiting.count) >= MAX_USERS_COUNT
  end

  def current_balance_amount
    users.sum(&:current_balance_amount)
  end
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates :uid, :provider, :user_id, presence: true
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  validates :user_id, :email, :code, presence: true
  delegate :name, to: :user, prefix: :user
  delegate :family, to: :user

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :waiting, -> { where(accepted_at: nil) }

  def accepted?
    accepted_at.present?
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  validates :amount, :date, presence: true
  validates :title, length: { maximum: 50 }
  belongs_to :user
  has_many :operation_categories, dependent: :destroy

  delegate :name, to: :user, prefix: true
  delegate :family, to: :user

  scope :incomes, -> { where(type: 'Operations::Income') }
  scope :outgos, -> { where(type: 'Operations::Outgo') }
  scope :by_period, ->(start, finish) { where(date: start..finish) }

  class << self
    def this_month
      start_date = Time.current.beginning_of_month
      end_date = Time.current.end_of_month
      by_period(start_date, end_date)
    end
  end
end

app/models/operation_category.rb
class OperationCategory < ApplicationRecord
  belongs_to :operation
  belongs_to :category
end

app/models/operations/outgo.rb
class Operations::Outgo < Operation
  has_many :categories,
           class_name: 'Categories::Outgo',
           through: :operation_categories
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  has_many :operations
  has_many :identities, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :balances, dependent: :destroy
  belongs_to :family, required: false

  delegate :title, :operations, to: :family, prefix: :family
  delegate :paid?, to: :family
  delegate :amount, to: :current_month_balance, prefix: :current_month_balance

  def current_month_balance
    current_year = Date.current.year
    current_month = Date.current.month
    balances.find_or_create_by(year: current_year, month: current_month)
  end

  def month_balance(year, month)
    balances.where(year: year, month: month).sum(:amount)
  end

  def current_balance_amount
    balances.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_invite

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.includes(:family).find(session[:user_id])
  end

  def login_user(user)
    return unless user
    session[:user_id] = user.id
  end

  def store_invite
    session[:invite] = params[:invite] if params[:invite]
  end

  helper_method :current_user
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    @form = InviteForm.new(invite_params)
    if @form.save
      flash[:success] = t('invites.flash.invite_sent')
    else
      flash[:error] = @form.errors.full_messages.join('<br>')
    end
    redirect_back(fallback_location: profile_path)
  end

  def destroy
    invite = Invite.find(params[:id])
    if invite.destroy
      flash[:success] = t('invites.flash.delete_success')
    else
      flash[:error] = invite.errors.full_messages.join('<br>')
    end
    redirect_back(fallback_location: profile_path)
  end

  private

  def invite_params
    params.require(:invite_form).permit(:email).merge(user: current_user)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @operations = OperationsView
                  .new(
                    current_user,
                    params[:type],
                    month: params[:month],
                    year: params[:year]
                  )
    @new_operation = OperationForm.new(type: params[:type])
  end

  def edit
  end

  def create
    @form = OperationForm.new(operation_params, current_user)
    if @form.save
      flash[:success] = t('operations.flash.created')
    else
      flash[:error] = t('operations.flash.not_created')
    end
    redirect_back(fallback_location: operations_path)
  end

  def update
  end

  def destroy
  end

  private

  def operation_params
    params
      .require(:operation_form)
      .permit(:type, :amount, :date, :title, :categories_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = UserAuthentificator
           .new(request.env['omniauth.auth'], session[:invite])
           .call
    if user
      login_user(user)
      flash[:notice] = t('common.login_succes')
    else
      flash[:error] = t('common.login_failed')
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('common.logout_success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_form = UserForm.new(current_user)
    @invite_form = InviteForm.new(user: current_user)
    @family = Family.includes(:users, :invites).find(current_user.family_id)
  end

  def update
    @user_form = UserForm.new(current_user, form_params)
    if @user_form.save
      flash[:success] = t('users.flash.updated')
    else
      flash[:error] = "#{t('users.flash.not_updated')}. "\
                      "#{@user_form.errors.full_messages.join('<br>')}"
    end
    redirect_back(fallback_location: profile_path)
  end

  private

  def form_params
    params.require(:user_form).permit(:family_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
  def used_operations_ratio(family)
    current_operations_count = family.operations.this_month.count
    "#{current_operations_count}/#{Family::FREE_MONTH_OPERATIONS_LIMIT}"
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
  def active?(controller_name, type = nil)
    controller.controller_name == controller_name && params[:type] == type
  end

  def side_menu_link_class(params, year, month)
    if year == params[:year].to_i && month == params[:month].to_i
      return 'active'
    end
    return 'active' if current_year_and_month?(params, year, month)
  end

  def current_year_and_month?(params, year, month)
    !params[:year] && !params[:month] &&
      year == Date.current.year &&
      month == Date.current.month
  end
end

app/views/layouts/_footer.slim
.row
  footer
    p &copy; pustserg 2016

app/views/layouts/_header.slim
.navbar.navbar-default.navbar-static-top
    .container
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to t(:app_name), root_path, class: 'navbar-brand'
      .navbar-collapse.collapse.navbar-responsive-collapse
        ul.nav.navbar-nav
          - if current_user
            li.nav-item class="#{'active' if active?('operations', 'outgo')}"
              = link_to t('operations.outgos'),
                        outgos_path, class: 'nav-link'
            li.nav-item class="#{'active' if active?('operations', 'income')}"
              = link_to t('operations.incomes'),
                        incomes_path
        ul.nav.navbar-nav.navbar-right.right
          = yield(:total) if content_for?(:total)
          = yield(:balance) if content_for?(:balance)
          - if current_user
            li.nav-item.dropdown
              = link_to current_user.name, '#',
                        class: 'nav-link dropdown-toggle',
                        'data-toggle' => 'dropdown', role: 'button',
                        'aria-haspopup' => "true", 'aria-expanded' => "false",
                        id: 'profile-dropdown'
              .dropdown-menu.text-right
                =link_to t('common.settings'), profile_path,
                         class: 'dropdown-item'
                br
                =link_to t('common.logout'), logout_path,
                         class: 'dropdown-item', method: :delete

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Money5"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body data-locale= I18n.locale
    = render 'layouts/header'
    = yield(:side_menu) if content_for?(:side_menu)
    .container class="#{controller.controller_name}"
      = bootstrap_flash
      = yield
    = render 'layouts/footer'

app/views/pages/index.slim
.jumbotron
  h1.display-3 Hello
  p.lead Yet Another Budget Program
  - unless current_user
    p.lead
      = link_to t('common.login'), '/auth/facebook',
                role: 'button', class: 'btn btn-primary btn-lg'