config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  resources :operations, except: :index
  get '/income/(:year)/(:month)',
      to: 'operations#index',
      as: :incomes,
      type: 'income'
  get '/outgo/(:year)/(:month)',
      to: 'operations#index',
      as: :outgos,
      type: 'outgo'

  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/profile', to: 'users#show', as: :profile
  resource :user, only: :update
  resources :invites, only: %i(create destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
  validates :amount, :year, :month, presence: true
  belongs_to :user
end

app/models/categories/income.rb
class Categories::Income < Category
  has_many :operations,
           class_name: 'Operations::Income',
           through: :operation_categories
end

app/models/categories/outgo.rb
class Categories::Outgo < Category
  has_many :operations,
           class_name: 'Operations::Outgo',
           through: :operation_categories
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 50 }
  validates :title, uniqueness: { scope: [:user_id, :type] }
  has_many :operation_categories, dependent: :destroy
  belongs_to :user

  delegate :family, to: :user
end

app/models/family.rb
class Family < ApplicationRecord
  # TODO: need to validate while user is creating
  MAX_USERS_COUNT = 3
  FREE_MONTH_OPERATIONS_LIMIT = 50
  has_many :users
  has_many :categories, through: :users
  has_many :operations, through: :users
  has_many :invites, through: :users

  def full?
    (users.count + invites.waiting.count) >= MAX_USERS_COUNT
  end

  def current_balance_amount
    users.sum(&:current_balance_amount)
  end
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates :uid, :provider, :user_id, presence: true
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  validates :user_id, :email, :code, presence: true
  delegate :name, to: :user, prefix: :user
  delegate :family, to: :user

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :waiting, -> { where(accepted_at: nil) }

  def accepted?
    accepted_at.present?
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  validates :amount, :date, presence: true
  validates :title, length: { maximum: 50 }
  belongs_to :user
  has_many :operation_categories, dependent: :destroy

  delegate :name, to: :user, prefix: true
  delegate :family, to: :user

  scope :incomes, -> { where(type: 'Operations::Income') }
  scope :outgos, -> { where(type: 'Operations::Outgo') }
  scope :by_period, ->(start, finish) { where(date: start..finish) }

  class << self
    def this_month
      start_date = Time.current.beginning_of_month
      end_date = Time.current.end_of_month
      by_period(start_date, end_date)
    end
  end
end

app/models/operation_category.rb
class OperationCategory < ApplicationRecord
  belongs_to :operation
  belongs_to :category
end

app/models/operations/income.rb
class Operations::Income < Operation
  has_many :categories,
           class_name: 'Categories::Income',
           through: :operation_categories
end

app/models/operations/outgo.rb
class Operations::Outgo < Operation
  has_many :categories,
           class_name: 'Categories::Outgo',
           through: :operation_categories
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  has_many :operations
  has_many :identities, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :balances, dependent: :destroy
  belongs_to :family, required: false

  delegate :title, :operations, to: :family, prefix: :family
  delegate :paid?, to: :family
  delegate :amount, to: :current_month_balance, prefix: :current_month_balance

  def current_month_balance
    current_year = Date.current.year
    current_month = Date.current.month
    balances.find_or_create_by(year: current_year, month: current_month)
  end

  def month_balance(year, month)
    balances.where(year: year, month: month).sum(:amount)
  end

  def current_balance_amount
    balances.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_invite

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.includes(:family).find(session[:user_id])
  end

  def login_user(user)
    return unless user
    session[:user_id] = user.id
  end

  def store_invite
    session[:invite] = params[:invite] if params[:invite]
  end

  helper_method :current_user
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    @form = InviteForm.new(invite_params)
    if @form.save
      flash[:success] = t('invites.flash.invite_sent')
    else
      flash[:error] = @form.errors.full_messages.join('<br>')
    end
    redirect_back(fallback_location: profile_path)
  end

  def destroy
    invite = Invite.find(params[:id])
    if invite.destroy
      flash[:success] = t('invites.flash.delete_success')
    else
      flash[:error] = invite.errors.full_messages.join('<br>')
    end
    redirect_back(fallback_location: profile_path)
  end

  private

  def invite_params
    params.require(:invite_form).permit(:email).merge(user: current_user)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @operations = OperationsView
                  .new(
                    current_user,
                    params[:type],
                    month: params[:month],
                    year: params[:year]
                  )
    @new_operation = OperationForm.new(type: params[:type])
  end

  def edit
  end

  def create
    @form = OperationForm.new(operation_params, current_user)
    if @form.save
      flash[:success] = t('operations.flash.created')
    else
      flash[:error] = t('operations.flash.not_created')
    end
    redirect_back(fallback_location: operations_path)
  end

  def update
  end

  def destroy
  end

  private

  def operation_params
    params
      .require(:operation_form)
      .permit(:type, :amount, :date, :title, :categories_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = UserAuthentificator
           .new(request.env['omniauth.auth'], session[:invite])
           .call
    if user
      login_user(user)
      flash[:notice] = t('common.login_succes')
    else
      flash[:error] = t('common.login_failed')
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('common.logout_success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_form = UserForm.new(current_user)
    @invite_form = InviteForm.new(user: current_user)
    @family = Family.includes(:users, :invites).find(current_user.family_id)
  end

  def update
    @user_form = UserForm.new(current_user, form_params)
    if @user_form.save
      flash[:success] = t('users.flash.updated')
    else
      flash[:error] = "#{t('users.flash.not_updated')}. "\
                      "#{@user_form.errors.full_messages.join('<br>')}"
    end
    redirect_back(fallback_location: profile_path)
  end

  private

  def form_params
    params.require(:user_form).permit(:family_title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
  def used_operations_ratio(family)
    current_operations_count = family.operations.this_month.count
    "#{current_operations_count}/#{Family::FREE_MONTH_OPERATIONS_LIMIT}"
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
  def active?(controller_name, type = nil)
    controller.controller_name == controller_name && params[:type] == type
  end

  def side_menu_link_class(params, year, month)
    if year == params[:year].to_i && month == params[:month].to_i
      return 'active'
    end
    return 'active' if current_year_and_month?(params, year, month)
  end

  def current_year_and_month?(params, year, month)
    !params[:year] && !params[:month] &&
      year == Date.current.year &&
      month == Date.current.month
  end
end

app/views/operations/_form.slim
#form.modal.fade tabindex='-1' role='dialog' aria-labelled-by='form' aria-hidden='true'
  .modal-dialog role='document'
    .modal-content
      .modal-header
        button.close type='button' data-dismiss='modal' aria-label=t('common.close')
          span aria-hidden='true' &times;
        h5.modal-title= t('operations.form_title')
      = form_for @new_operation, url: operations_path do |f|
        .modal-body.container
          = f.hidden_field :type
          .form-group.row
            = f.label :title, class: 'col-form-label col-md-2'
            .col-md-4
              = f.text_field :title, class: 'form-control'
          .form-group.row
              = f.label :amount, class: 'col-form-label col-md-2'
              .col-md-4
                = f.number_field :amount, class: 'form-control'
          .form-group.row
              = f.label :date, class: 'col-form-label col-md-2'
              .col-md-4
                = f.text_field :date, class: 'form-control datepicker'
          .form-group.row
            = f.label :categories_list, class: 'col-form-label col-md-2'
            .col-md-4
              = f.hidden_field :categories_list, class: 'form-control'
              = text_field_tag :tags_input, '', class: 'form-control'
          .form-group.row
            .col-md-4.col-md-offset-2#tags
        .modal-footer
          .form-group
            = f.submit t('common.save'), class: 'btn btn-success'

app/views/operations/_operation.html.slim
.row
  .card.col-md-8.col-md-offset-2.col-xs-10.col-xs-offset-1
    .card-header
      => l operation.date
      => operation.user_name
    .card-block
      .col-md-8.col-xs-8
        = operation.title
      .col-md-4.col-xs-4.text-right
        = number_to_currency operation.amount

app/views/operations/_side_menu.slim
.operations-side-menu.opener.side-menu
  button.btn.btn-default.btn-lg#open-button
    span.glyphicon.glyphicon-calendar
.operations-side-menu.side-menu.menu.hidden
  button.btn.btn-default.btn-lg#close-button
    span.glyphicon.glyphicon-chevron-left
  .panel-group#my-accordion
    - @operations.dates_hash_for_side_menu.each_with_index do |(year, months), i|
      - visible = params[:year].to_i == year || (params[:year].nil? && i.zero?)
      .panel.panel-default
        .panel-heading.headingYear rol='tab'
          span data-toggle="#{year}"
            = year
        .panel-body data-toggled-by="#{year}" class="#{'hidden' unless visible }"
          ul
            - months.each do |month|
              li= link_to t("common.dates.months.#{Date::MONTHNAMES[month]}"),
                  url_for(year: year, month: month),
                  class: side_menu_link_class(params, year, month)

app/views/operations/index.slim
- if current_user
  = content_for :total
    li.nav-item.total
      = "#{t('operations.total')}: #{number_to_currency(current_user.family.current_balance_amount)}"
= content_for :side_menu
  = render 'side_menu'
- if @new_operation.type && OperationPolicy.new(current_user).create?
  .row.add-new
    = link_to  new_operation_path, class: 'btn new-operation btn-primary col-md-6 col-md-offset-3 col-xs-12' do
      span.glyphicon.glyphicon-plus
      '&nbsp;
      = t("operations.create_#{@new_operation.type}")
= render partial: 'operation', collection: @operations.index
= render 'form'

app/views/users/show.slim
.panel.panel-default
  .panel-body
    .col-md-6
      h4= t('users.account_settings')
    .col-md-6.actions.text-right
      button.btn.btn-danger.toggle-user-form
        = t('common.cancel')
      button.btn.btn-info.toggle-user-form
        = t('common.edit')
    .col-md-12.user-form
      = form_for @user_form, url: user_path(@user_form.user), method: :put do |f|
        .form-group.row
          = f.label :family_title, class: 'col-form-label col-md-2'
          .col-md-4.value
            p.value= @user_form.family_title
          .col-md-4.form-input
            = f.text_field :family_title, class: 'form-control'
        .form-group.row
          = f.label :family_paid, class: 'col-form-label col-md-2'
          .col-md-4
            p= @user_form.family_paid? ? t('common.paid') : t('common.free')
        - unless @user_form.family_paid?
          .form-group.row
            label.col-form-label.col-md-2
              = t('family.current_ratio_free_operations')
            .col-md-4
              p= used_operations_ratio(@family)
        .form-group.form-input.text-right
          = f.submit t('common.save'), class: 'btn btn-success'
.panel.panel-default
  .panel-body
    .col-md-10.users_list
      dl.dl-horizontal
        dt= t('users.list')
        dd
          ul.list-unstyled
            - @family.users.each do |user|
              li= user.name
      dl.dl-horizontal
        dt= t('users.invites')
        dd
          ul.list-unstyled
            - @family.invites.waiting.each do |invite|
              li
                => invite.email
                = link_to invite_path(invite),
                          method: :delete, class: 'btn btn-danger btn-xs' do
                  span.glyphicon.glyphicon-remove
    - unless @family.full?
      .col-md-12.actions.text-right
        button.btn.btn-danger.toggle-invite-form
          = t('common.cancel')
        button.btn.btn-primary.toggle-invite-form
          = t('family.add_user')
      .col-md-12.invite-form
        = form_for @invite_form, url: invites_path do |f|
          .form-group.row.form-input
            = f.label :email, class: 'col-form-label col-md-2'
            .col-md-4
              = f.text_field :email, class: 'form-control'
          .form-group.form-input.text-right
            = f.submit t('common.invite'), class: 'btn btn-success'